update gitignore alias

diff --git a/git_template/hooks/post-checkout b/git_template/hooks/post-checkout
--- a/git_template/hooks/post-checkout
+++ b/git_template/hooks/post-checkout
@@ -1,9 +1,3 @@
 #!/bin/sh
-
-local_hook="$HOME"/.git_template.local/hooks/post-checkout
-
-if [ -f "$local_hook" ]; then
-  . "$local_hook";
-fi
-
-.git/hooks/ctags >/dev/null 2>&1 &
+command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/post-checkout'.\n"; exit 2; }
+git lfs post-checkout "$@"
